[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/free/*"
  to = "https://api-free.deepl.com/v2/translate"
  status = 200
  force = true

[[redirects]]
  from = "/api/pro/*"
  to = "https://api.deepl.com/v2/translate"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
